# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      DATABASEHOSTNAME:  ${{ secrets.DATABASEHOSTNAME }}
      DATABASEUSERNAME: ${{ secrets.DATABASEUSERNAME }}
      DATABASEPASSWORD: ${{ secrets.DATABASEPASSWORD }}
      DATABASENAME: ${{ secrets.DATABASENAME }}
      DATABASEPORT: ${{ secrets.DATABASEPORT }}
      DATABASESSLBASE64: ${{ secrets.DATABASESSLBASE64 }}
      SERVER_IP: ${{ secrets.SERVER_IP }}
      SERVER_PATH: ${{ secrets.SERVER_PATH }}
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      

    strategy:
      matrix:
        node-version: [ 21.x ]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run start &
    - run: npm test
    
    - name: Compress build directory and additional files
      run: tar -czvf deploy.tar.gz build ./src/backend/main.js ./src/backend/db.js

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Deploy to server using sshpass
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
        scp deploy.tar.gz root@${{ secrets.SERVER_IP }}:${{ secrets.SERVER_PATH }}
        
