# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Node.js CI and Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATABASEHOSTNAME:  ${{ secrets.DATABASEHOSTNAME }}
      DATABASEUSERNAME: ${{ secrets.DATABASEUSERNAME }}
      DATABASEPASSWORD: ${{ secrets.DATABASEPASSWORD }}
      DATABASENAME: ${{ secrets.DATABASENAME }}
      DATABASEPORT: ${{ secrets.DATABASEPORT }}
      DATABASESSLBASE64: ${{ secrets.DATABASESSLBASE64 }}
      SERVER_IP: ${{ secrets.SERVER_IP }}
      SERVER_PATH: ${{ secrets.SERVER_PATH }}
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}

    strategy:
      matrix:
        node-version: [ 21.x ]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build --if-present

    - name: Run tests
      run: npm test

    - name: Compress build directory and additional files
      run: tar -czvf deploy.tar.gz build ./src/backend/main.js ./src/backend/db.js

    - name: Generate SSH key
      id: gen_ssh
      run: |
        ssh-keygen -t rsa -b 4096 -m PEM -f ${{ github.workspace }}/deploy_key -q -N ""
        cat ${{ github.workspace }}/deploy_key.pub

    - name: Deploy Public Key to Server
      run: |
        echo "${{ secrets.SSH_PUBLIC_KEY }}" | sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} 'mkdir -p ~/.ssh && cat >> ~/.ssh/authorized_keys'
      env:
        SSH_PUBLIC_KEY: ${{ github.workspace }}/deploy_key.pub

    - name: Deploy to Server
      run: |
        scp -i ${{ github.workspace }}/deploy_key deploy.tar.gz root@${{ secrets.SERVER_IP }}:${{ secrets.SERVER_PATH }}
      env:
        DEPLOY_KEY: ${{ github.workspace }}/deploy_key

    - name: Cleanup SSH Keys
      run: |
        rm -f ${{ github.workspace }}/deploy_key
        rm -f ${{ github.workspace }}/deploy_key.pub
